# Generated by Django 3.0.7 on 2020-06-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='station.Station')),
            ],
        ),
    ]
