# Generated by Django 3.0.7 on 2020-06-17 08:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('prefered_language', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('is_admin', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('status', models.CharField(max_length=4)),
                ('test_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('skill', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_manpower', models.IntegerField(default=0)),
                ('required_manpower', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('total_question', models.IntegerField()),
                ('passing_marks', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Stage')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Station')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField()),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=50)),
                ('option_b', models.CharField(max_length=50)),
                ('option_c', models.CharField(max_length=50)),
                ('option_d', models.CharField(max_length=50)),
                ('correct_option', models.CharField(max_length=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.TestHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResultQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.TestQuestion')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.ResultHeader')),
            ],
        ),
        migrations.AddField(
            model_name='resultheader',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.TestHeader'),
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Employee')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Stage')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Station')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Station'),
        ),
    ]
