# Generated by Django 3.0.6 on 2020-05-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_token', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=7)),
                ('current_station', models.CharField(default='Some station', max_length=200)),
                ('mobile', models.CharField(max_length=12)),
                ('doj', models.DateField(auto_now_add=True)),
                ('language_preference', models.CharField(default='English', max_length=200)),
                ('createdOn', models.DateField(auto_now_add=True)),
                ('createdBy', models.CharField(default='Some Admin', max_length=200)),
                ('isAdmin', models.BooleanField(default=True)),
            ],
        ),
    ]
