# Generated by Django 3.0.7 on 2020-07-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestions',
            name='correct_option',
            field=models.CharField(default='Op1', max_length=5),
            preserve_default=False,
        ),
    ]
