# Generated by Django 3.0.7 on 2020-07-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='shift',
            new_name='current_shift',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='stage',
            new_name='current_stage',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='station',
            new_name='current_station',
        ),
    ]
