# Generated by Django 3.0.7 on 2020-06-15 11:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks_Obtained', models.FloatField()),
                ('Total_Marks', models.FloatField()),
                ('Test_Date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Current_Manpower', models.IntegerField(default=0)),
                ('Required_Manpower', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Total_Question', models.IntegerField()),
                ('Passing_Percent', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('Created_On', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Stage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Stage')),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Station')),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='isAdmin',
            new_name='Is_Admin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='createdOn',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_station',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='doj',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_token',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='language_preference',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mobile',
        ),
        migrations.AddField(
            model_name='employee',
            name='Contact',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Created_By',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Created_On',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='Date_Of_Joining',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='Gender',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Language_Preference',
            field=models.CharField(default='hindi', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Name',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Token',
            field=models.IntegerField(default=1232134),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Num', models.IntegerField()),
                ('Question', models.TextField()),
                ('Option_A', models.CharField(max_length=50)),
                ('Option_B', models.CharField(max_length=50)),
                ('Option_C', models.CharField(max_length=50)),
                ('Option_D', models.CharField(max_length=50)),
                ('Correct_Option', models.CharField(max_length=1)),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.TestHeader')),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='Station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Station'),
        ),
        migrations.CreateModel(
            name='ResultQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.CharField(max_length=1)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.TestQuestion')),
                ('Result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.ResultHeader')),
            ],
        ),
        migrations.AddField(
            model_name='resultheader',
            name='Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Employee'),
        ),
        migrations.AddField(
            model_name='resultheader',
            name='Test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.TestHeader'),
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.IntegerField()),
                ('Test_Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Employee')),
                ('Stage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Stage')),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Station')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Station',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.DO_NOTHING, to='adminview.Station'),
            preserve_default=False,
        ),
    ]
