# Generated by Django 3.0.7 on 2020-06-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=200)),
                ('test_station', models.CharField(max_length=20)),
                ('test_stage', models.CharField(max_length=20)),
                ('no_of_questions', models.IntegerField()),
                ('test_time', models.IntegerField()),
                ('max_marks', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='createdOn',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='isAdmin',
            new_name='is_admin',
        ),
    ]
