# Generated by Django 3.0.6 on 2020-07-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0002_auto_20200711_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(),
        ),
    ]
