# Generated by Django 3.0.7 on 2020-06-05 10:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
        ('stage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('Language_Preference', models.CharField(max_length=50)),
                ('Date_Of_Joining', models.DateField()),
                ('Created_On', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Created_By', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='station.Station')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.IntegerField()),
                ('Test_Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Employee')),
                ('Stage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stage.Stage')),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='station.Station')),
            ],
        ),
    ]
