# Generated by Django 3.0.7 on 2020-06-05 10:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Question', models.IntegerField()),
                ('Passing_Percent', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('Created_On', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Stage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stage.Stage')),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='station.Station')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Num', models.IntegerField()),
                ('Question', models.TextField()),
                ('Option_A', models.CharField(max_length=50)),
                ('Option_B', models.CharField(max_length=50)),
                ('Option_C', models.CharField(max_length=50)),
                ('Option_D', models.CharField(max_length=50)),
                ('Correct_Option', models.CharField(max_length=1)),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='question.TestHeader')),
            ],
        ),
    ]
